
'use client';

import * as Tone from 'tone';
import type { MusicKey, MusicScale, AutopilotStyle } from '@/app/page';
import type { WorkerEvent, WorkerResponse, AutopilotPart } from './autopilot-worker';
import type { AudioEngine } from './audio-engine';

// This cache will store worker instances to avoid recreating them on every style switch if not necessary.
// However, the current logic creates a new worker for each switch to ensure a clean state.
const workerCache: Partial<Record<AutopilotStyle, Worker>> = {};

export class AutopilotEngine {
    private audioEngine: AudioEngine;
    private activeWorker: Worker | null = null;
    private currentStyle: AutopilotStyle | null = null;
    private isAutopilotOn = false;
    private tickLoop: Tone.Loop | null = null;

    private lastKnownState: {
        bpm: number;
        key: MusicKey;
        scale: MusicScale;
        parts: Record<AutopilotPart, boolean>;
        style: AutopilotStyle;
    } = {
        bpm: 90, // A good starting tempo
        key: 'C',
        scale: 'Major Pentatonic',
        parts: { bass: true, accompaniment: true, melody: true, effects: true },
        style: 'Ambient'
    };

    constructor(audioEngine: AudioEngine) {
        this.audioEngine = audioEngine;
        this.initialize();
    }

    private initialize() {
        // This loop is the heart of the autopilot. It sends a 'tick' to the active worker
        // in perfect sync with the master Tone.Transport.
        this.tickLoop = new Tone.Loop(time => {
            this.postMessageToActiveWorker({ type: 'tick', time });
        }, '16n').start(0);

        // Ensure worker state is reset when transport stops globally
        this.handleTransportStop();
        Tone.Transport.on('stop', this.handleTransportStop);
    }
    
    // This is the single point of contact from a worker to the main thread.
    // It takes the note generated by the worker and passes it to the AudioEngine to be played.
    private handleWorkerMessage = (event: MessageEvent<WorkerResponse>) => {
        if (!this.isAutopilotOn) return;

        const { type, note, time } = event.data;
        if (type === 'playNote' && note) {
            this.audioEngine.playAutopilotEvent(note, time);
        }
    }

    private handleTransportStop = () => {
         this.postMessageToActiveWorker({ type: 'stop' });
    };

    // Dynamically gets the correct worker file based on the selected style.
    private getWorker(style: AutopilotStyle): Worker {
        // Terminate any existing cached worker for this style to ensure a fresh start.
        if (workerCache[style]) {
            workerCache[style]?.terminate();
        }

        let workerFileName: string;
        switch(style) {
            case 'Toccata':     workerFileName = 'toccata.worker.js'; break;
            case 'Promenade':   workerFileName = 'promenade.worker.js'; break;
            case 'House':       workerFileName = 'house.worker.js'; break;
            case 'Wind':        workerFileName = 'wind.worker.js'; break;
            case 'Sequence':    workerFileName = 'sequence.worker.js'; break;
            case 'Chimes':      workerFileName = 'chimes.worker.js'; break;
            case 'Drone':       workerFileName = 'drone.worker.js'; break;
            case 'Space':       workerFileName = 'space.worker.js'; break;
            case 'Ambient':
            default:            workerFileName = 'ambient.worker.js'; break;
        }

        try {
            // Workers are in the public folder, so we can use a direct path.
            const workerPath = `/assets/workers/${workerFileName}`;
            const worker = new Worker(workerPath);
            
            // Set up the message handler for the new worker.
            worker.onmessage = this.handleWorkerMessage;
            worker.onerror = (e) => console.error(`Error in worker ${style}:`, e);

            workerCache[style] = worker;
            return worker;
        } catch (e) {
            console.error(`Failed to construct Worker for style ${style}:`, e);
            if (style !== 'Ambient') return this.getWorker('Ambient'); // Fallback to Ambient
            throw e;
        }
    }
    
    private postMessageToActiveWorker(message: WorkerEvent) {
        this.activeWorker?.postMessage(message);
    }
    
    public setTempo(bpm: number) {
        this.lastKnownState.bpm = bpm;
        this.postMessageToActiveWorker({ type: 'setTempo', bpm: bpm });
    }

    public setHarmony(key: MusicKey, scale: MusicScale) {
        this.lastKnownState.key = key;
        this.lastKnownState.scale = scale;
        this.postMessageToActiveWorker({ type: 'setHarmony', key, scale });
    }

    public setAutopilotParts(parts: Record<AutopilotPart, boolean>) {
        this.lastKnownState.parts = parts;
        this.postMessageToActiveWorker({ type: 'setParts', parts: parts });
    }
    
    // The main logic for starting, stopping, and switching autopilot styles.
    public setAutopilot(isOn: boolean, style: AutopilotStyle) {
        const styleChanged = this.currentStyle !== style;
        
        // If turning off or changing style, stop the current worker.
        if (this.activeWorker && (!isOn || styleChanged)) {
            this.postMessageToActiveWorker({ type: 'stop' });
            this.activeWorker.terminate(); // Terminate to clean up resources
            this.activeWorker = null;
            this.currentStyle = null;
        }

        this.isAutopilotOn = isOn;

        if (isOn) {
            // Get or create a new worker for the selected style.
            this.activeWorker = this.getWorker(style);
            this.currentStyle = style;
            
            // Sync the new worker with the latest state.
            this.syncWorkerState();
            
            // If the master transport is already running, tell the worker to start generating notes immediately.
            // If not, it will start automatically when the user presses play.
            if (Tone.Transport.state === 'started') {
                this.postMessageToActiveWorker({ type: 'start' });
            }
        }
    }

    private syncWorkerState() {
        if (!this.activeWorker) return;
        this.postMessageToActiveWorker({ type: 'setTempo', bpm: this.lastKnownState.bpm });
        this.postMessageToActiveWorker({ type: 'setHarmony', key: this.lastKnownState.key, scale: this.lastKnownState.scale });
        this.postMessageToActiveWorker({ type: 'setParts', parts: this.lastKnownState.parts });
        this.postMessageToActiveWorker({ type: 'setStyle', style: this.lastKnownState.style }); // Pass style for context
    }

    public dispose() {
        this.tickLoop?.dispose();
        Tone.Transport.off('stop', this.handleTransportStop);
        Object.values(workerCache).forEach(worker => worker?.terminate());
        this.activeWorker = null;
    }
}
