
export const guideContent = `
# EtherMusic Quick Guide

Welcome to EtherMusic! This is a simple guide to get you started on making cool sounds.

## What is This? (And What It Isn't)

**This is not a simplified Digital Audio Workstation (DAW) or a DJ mixer.** You won't produce a studio-quality track here.

Instead, think of it as a **virtual music box**, a "Neuro-Meditation Sound Processor." It's an instrument that anyone can play, designed for relaxation, focus, and self-expression. We built it for everyone who loves music but feels intimidated by complex software and music theory. Here, you can't make a mistake.

Our application is at the intersection of a creative tool, a meditation aid, and a digital wellness gadget. It is not for professional musicians, but for a wide audience that appreciates ambient music, mindfulness, and is looking for new forms of self-expression and relaxation.

This is truly a tool for those who carry music in their souls but, for various reasons, cannot express it through traditional instruments. It gives everyone the opportunity to feel like a composer.

## The Big Pads (Theremins)

There are two large, glowing pads. They are your main instruments.

*   **How to Play:** Touch a pad with your finger (or click with a mouse).
*   **Left to Right:** Controls the **pitch** (the note you hear).
*   **Up and Down:** Controls the **volume** (how loud the note is).

### Melody Pad (Right, Purple)

*   This is for your main tune. It's polyphonic, allowing you to play up to three notes at the same time.
*   **Settings:** Use the \`Settings\` button at the top of the pad to open a panel where you can change the **Instrument** (\`synth\`, \`organ\`, \`theremin\`, \`glass\`), **Music Key**, and **Music Scale**. These settings affect both your playing and the music generated by the **Autopilot**, creating a unified sound.

### Bass Pad (Left, Blue)

*   This is for your bass line. It's polyphonic, meaning you can play up to three notes at the same time to create chords.
*   **Latch (\`Anchor\` Icon):** "Holds" notes for you. Tap the switch to turn Latch mode on.
    *   **To add a note:** Tap on the pad to start a note. A glowing orb will appear.
    *   **To remove a note:** Tap on an existing orb or in the same spot again to stop that specific note.
    *   You can have up to three notes latched at once.

## Bottom Control Bar

Here you control the rhythm and atmosphere. You can change any of these settings on the fly, even during playback!

*   **Beats:** Tap this to open a menu and choose a pre-made drum pattern based on high-quality samples. Beats are divided into **Meditative** (slow, sparse) and **Classic** (structured, rhythmic) categories. Select \`Off\` to have no drums.
*   **Tempo:** Tap this to open a slider that changes the speed of the beat (BPM - Beats Per Minute).
*   **Mixer:** Tap this to open the volume controls. You can adjust the volume for the **Melody**, **Bass**, **Latch**, **Drums**, and even случайные **Effects** separately.
*   **Autopilot:** This button opens the Autopilot settings, where you can turn it on/off and select a generation style.

### Autopilot Mode

Don't want to play yourself? Turn on the **Autopilot**!
*   **Autopilot (\`Bot\` Icon):** Turns on the automatic music generator. The app will start creating its own complex parts for bass, accompaniment, and melody using arpeggiators and syncopation. You can still play along on the melody pad!
*   **Style:** Choose a style to change how the Autopilot generates music:
    *   **Ambient:** Slow, evolving soundscapes.
    *   **Sequence:** Hypnotic, repeating arpeggios.
    *   **Water:** Flowing, arpeggiated patterns resembling water droplets.
    *   **Air:** Light, spacious, and "breathing" musical phrases.
    *   **Toccata:** Virtuosic and dramatic patterns inspired by the works of J.S. Bach.
    *   **Promenade:** Stately and majestic themes reminiscent of Mussorgsky's "Pictures at an Exhibition".
    *   **Space:** A slow, pulsing arpeggio in the style of Jean-Michel Jarre, with occasional "meteor" sound effects.

## Top Right Controls

*   **Play/Pause:** Starts and stops the master clock and the drum sequence.
*   **Stop:** Stops all sounds immediately.
*   **Record (\`Circle\` Icon):** Press it to start recording your session. Press it again to stop. Your recording will be downloaded automatically as a \`.webm\` file.
*   **Exit (\`Power\` Icon):** Opens a confirmation dialog to close the app.

## A Note on Performance

**Important:** On older or less powerful mobile devices, using the **Latch** mode simultaneously with the **Autopilot** and the **Drum Machine** can sometimes lead to sound artifacts like clicks, freezes, or stuttering. The audio engine is powerful, but it requires significant resources.

If you experience this, we recommend using these features separately for the smoothest experience (e.g., play manually with the drum machine, or use the Autopilot without the Latch mode).

Enjoy the process and let the music you create reflect your inner state.
`;
